checkpoint: ./trained_models/DDAffinity.pt
early_stoppingdir: ./early_stopping
model:
  encoder:
    node_feat_dim: 128
    pair_feat_dim: 64
    num_layers: 3
  node_features: 128
  edge_features: 128
  hidden_dim: 128
  seq_neighbours:  1
  seq_nonneighbours: 7
  num_encoder_layers: 3
  num_decoder_layers: 3
  k_neighbors: 16
  dropout: 0.1
  augment_eps: 0.2
  patch_size: 256
train:
  loss_weights:
    loss_mse: 1.0
  max_iters: 100000
  val_freq: 1000
  early_stop_iters: 70000
  batch_size: 16
  seed: 2022
  max_grad_norm: 100.0
  optimizer:
    type: adam
    lr: 6.e-4
    weight_decay: 0.0
    beta1: 0.9
    beta2: 0.999

# Data configuration for PyRosetta structures
data:
  csv_path: ./data/SKEMPI2/SKEMPI2.csv
  pdb_wt_dir: ./data/SKEMPI2/SKEMPI2_cache/wildtype
  pdb_mt_dir: ./data/SKEMPI2/SKEMPI2_cache/optimized
  cache_dir: ./data/SKEMPI2/SKEMPI2_cache/entries_cache
  max_structures: 3000
  train: !include ../common/data_train_chain.yml
  val: !include ../common/data_val_chain.yml
  is_single: 2 