checkpoint: ./trained_models/DDAffinity.pt
# checkpoint: ./trained_models/M1340.pt

early_stoppingdir: ./early_stopping
model:
  encoder:
    node_feat_dim: 128
    pair_feat_dim: 64
    num_layers: 3
  node_features: 128
  edge_features: 128
  hidden_dim: 128
  num_encoder_layers: 3
  num_decoder_layers: 3
  seq_neighbours: 3
  seq_nonneighbours: 7
  k_neighbors: 16
  dropout: 0.1
  augment_eps: 0.2
  patch_size: 256

data:
  csv_path: ./data/SKEMPI2/SKEMPI2_SPR_exclusive_clean.csv
  pdb_wt_dir: ./data/SKEMPI2/SKEMPI2_cache/wildtype
  pdb_mt_dir: ./data/SKEMPI2/SKEMPI2_cache/optimized
  cache_dir: ./data/SKEMPI2/SKEMPI2_cache_spr/entries_cache
  # csv_path: ./data/SKEMPI2/M1340.csv
  # pdb_wt_dir: ./data/SKEMPI2/M1340_cache/wildtype
  # pdb_mt_dir: ./data/SKEMPI2/M1340_cache/wildtype
  # cache_dir: ./data/SKEMPI2/M1340_cache/entries_cache
#  csv_path: ./data/SKEMPI2/S1131.csv
#  pdb_wt_dir: ./data/SKEMPI2/S1131_cache/wildtype
#  pdb_mt_dir: ./data/SKEMPI2/S1131_cache/optimized
#  cache_dir: ./data/SKEMPI2/S1131_cache/entries_cache
  # csv_path: ./data/SKEMPI2/M1707.csv
  # pdb_wt_dir: ./data/SKEMPI2/M1707_cache/wildtype
  # pdb_mt_dir: ./data/SKEMPI2/M1707_cache/optimized
  # cache_dir: ./data/SKEMPI2/M1707_cache/entries_cache
#  csv_path: ./data/SKEMPI2/S285.csv
#  pdb_wt_dir: ./data/SKEMPI2/S285_cache/wildtype
#  pdb_mt_dir: ./data/SKEMPI2/S285_cache/optimized
#  cache_dir: ./data/SKEMPI2/S285_cache/entries_cache
  train: !include ../common/data_train_chain.yml
  val: !include ../common/data_val_chain.yml
  is_single: 2

train:
  loss_weights:
    loss_mse: 1.0
  max_epochs: &max_epochs 75   # 300
  val_freq: 5
  early_stopping_epoch: 30     # 250
  batch_size: 32

  seed: 2024
  max_grad_norm: 100.0
  optimizer:
    type: adam
    lr: 6.e-4
    weight_decay: 0.0
    beta1: 0.9
    beta2: 0.999
    # type: warm_up
    # warmup: 8000
    # d_model: 128
    # step: 0
    # factor: 1

